version: '3'

services:

  app:
    image: 'keysafe-backend-app:latest'
#    build:
#      context: .
    container_name: keysafe-backend-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - keysafe
    healthcheck:
      test: curl --fail http://localhost:8080/status || exit 1
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s

  db:
    container_name: keysafe-postgres-database
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata

    env_file:
      - ".env"
    networks:
      - keysafe
    volumes:
      - ~/keysafe/backend/db/pgdata:/var/lib/postgresql/data/pgdata
      - ./integration/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  keysafe:
    driver: bridge
